name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Set Execution Permissions for wc.py
      run: chmod +x prog/wc.py

    - name: Set Execution Permissions for gron.py
      run: chmod +x prog/gron.py

    - name: Debug Information
      run: |
        ls -l
        pwd
        echo "Current directory contents:"
        ls -R
        echo "Executable permissions for wc.py:"
        ls -l prog/wc.py
        file prog/wc.py
        echo "Executable permissions for gron.py:"
        ls -l prog/gron.py
        file prog/gron.py

    - name: Run tests
      run: |
        chmod +x prog/wc.py  # Ensure executable permissions
        chmod +x prog/gron.py  # Ensure executable permissions
        python test.py
